In [17]:
a = 1; print(type(a))

<class 'int'>


마지막 줄만 보여짐
강제로 다 보여지게 하는 게 Print
소수점이 있는 것을 float
정수 int

In [1]:
a = 1; a = float(a); print(type(a))

<class 'float'>


In [19]:
a = 1.2; a = int(a); print(type(a))

<class 'int'>


In [20]:
a = '123'; print(type(a)); print(a[1])

<class 'str'>
2


Pyhon 에서는 0 이 첫 번째
제일 처음꺼는 0,  -1 을 쓰면 아무리 길더라도 맨 끝에 것이 나오고, -2는 끝에서 두 번째 있는것. 

In [21]:
a = '123'; a = list(a); print(type(a)); print(a); print(a[2])

<class 'list'>
['1', '2', '3']
3


In [22]:
a = [1,'2', [3, '4']]; print(type(a)); print(a[0]); print(a[1]); print(a[2])

<class 'list'>
1
2
[3, '4']


대 괄호, 중간에 콤마로 구분 돼있으면 반드시 list. 중간이 꼭 숫자일 필요는 없음

In [23]:
a = (1,'2', [3, '4']); print(type(a)); print(a[0]); print(a[1]); print(a[2])

<class 'tuple'>
1
2
[3, '4']


In [24]:
a =	{"a": "apple", "b": "orange", "c": 2014}
print(type(a))
print(a["a"])

<class 'dict'>
apple


a=[1,2,'ab',(4,5)] 이런 것도 리스트이다.

In [27]:
a=[(1,2,3), (3,8,0)]
print(type(a))
a

<class 'list'>


[(1, 2, 3), (3, 8, 0)]

a[-1][0] 리스트에서 마지막 꺼, 그 중에 첫 번째. 

In [28]:
import numpy as np
b = np.array(a)
print(b)
print(type(b))

[[1 2 3]
 [3 8 0]]
<class 'numpy.ndarray'>


In [29]:
print(b*b)

[[ 1  4  9]
 [ 9 64  0]]


In [30]:
c = np.matrix(b)
print(c)
print(type(c))

[[1 2 3]
 [3 8 0]]
<class 'numpy.matrixlib.defmatrix.matrix'>


In [31]:
c*c

ValueError: shapes (2,3) and (2,3) not aligned: 3 (dim 1) != 2 (dim 0)

In [32]:
c*c.T

matrix([[14, 19],
        [19, 73]])